version: "3"

services:
  reaper:
    image: leslieleung/reaper:v0.0.0
    environment:
      # set the timezone to be used by cron schedule
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Asia/Shanghai
    volumes:
      # config file path, modify it to yours
      - ${pwd}/config/example.config.yaml:/config.yaml
      # data path, to store downloaded repo, modify it to yours
      # the in-container path need to be the same as defined in config file
      - ${pwd}/repo:/repo
    # by default archives all repositories defined in configuration.
    command: ["run"]
    # or just archives a single repository defined in configuration.
    # command: ["rip", "reaper"]
    # run as daemon
    # command: ["daemon"]