repository:
  - name: reaper
    url: github.com/leslieleung/reaper
    cron: "0/3 * * * *"
    storage:
      - localFile
      - blackblaze

storage:
  - name: localFile
    type: file
    path: ./repo
  - name: backblaze
    type: s3
    endpoint: s3.us-west-000.backblazeb2.com
    region: us-west-000
    bucket: your-bucket-name
    accessKeyID: your-access-key-id
    secretAccessKey: your-secret-access-key